name: cron
on:
  schedule:
    - cron: '* * * * *'

jobs: 
  cronjob:
    runs-on: ubuntu-latest
    steps:
      - name: Clone our Repo
        uses: actions/checkout@v3

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

     - name: Run Python script
        run: python 01.hello.py     